import { v } from "convex/values";
import { responseIdentity } from "./response_identity";
export const displayIdentity = v.object({ sceneId: v.string(), displayedAtMs: v.number(), token: v.string() });
const identity = v.object({
  sessionAttemptId: v.string(),
  originSourceId: v.number(),
  owningSourceId: v.number(),
  evaluatedSceneIndex: v.number(),
  transcriptRevision: v.number(),
  answerVersion: v.string(),
  correlationKey: v.string(),
  responseIdentity,
  choreographyEpoch: v.number(),
  playbackAttemptId: v.string(),
});
export const localPlayback = v.object({
  type: v.literal("local_playback"),
  provenance: v.literal("application_finite_audio"),
  role: v.union(v.literal("acknowledgment"), v.literal("instructional_help"), v.literal("clarification")),
  sourceId: v.number(),
  identity,
  assetId: v.string(),
  assetSha256: v.string(),
  text: v.string(),
  display: displayIdentity,
  state: v.union(
    v.literal("requested"),
    v.literal("ready"),
    v.literal("started"),
    v.literal("media_ended"),
    v.literal("completed"),
    v.literal("interrupted"),
    v.literal("superseded"),
    v.literal("stopped"),
    v.literal("source_retired"),
    v.literal("failed"),
  ),
  reason: v.optional(v.string()),
  clock: v.literal("browser.performance.now"),
  observedAt: v.number(),
  sessionClockOrigin: v.optional(v.number()),
  sessionAtMs: v.optional(v.number()),
  mediaTime: v.optional(v.number()),
  duration: v.optional(v.number()),
  renderFence: v.optional(v.number()),
  outputTimestamp: v.optional(
    v.object({ contextTime: v.optional(v.number()), performanceTime: v.optional(v.number()) }),
  ),
  baseLatency: v.optional(v.number()),
  outputLatency: v.optional(v.number()),
});
export const choreographyPhase = v.object({
  type: v.literal("choreography_phase"),
  provenance: v.literal("application_controller"),
  sessionAttemptId: v.string(),
  choreographyEpoch: v.number(),
  correlationKey: v.string(),
  phase: v.union(
    v.literal("accepted_pending_ack"),
    v.literal("ack_playing"),
    v.literal("ack_draining"),
    v.literal("ack_completed"),
    v.literal("transition_waiting_display"),
    v.literal("next_question_pending"),
    v.literal("next_question_released"),
    v.literal("superseded"),
    v.literal("stopped"),
    v.literal("failed"),
  ),
  display: displayIdentity,
  questionToken: v.string(),
  questionStatus: v.union(v.literal("pending"), v.literal("authorized_delivery_unknown"), v.literal("cancelled")),
  reason: v.optional(v.string()),
  transitionFragmentKeys: v.optional(v.array(v.string())),
});
