"use client";

import { useEffect, useRef, useState } from "react";
import {
  recordingOffsetSeconds,
  type DurableSessionRef,
  type TimelineEvent,
  type InspectableSessionRecord,
  type SessionRecordReader,
} from "@/lib/session-recorder";

import { EvidenceDetail } from "./evidence-detail";
import { ParentReviewPanel } from "./parent-review-panel";

function TimelineDetail({ event }: { event: TimelineEvent }) {
  switch (event.type) {
    case "sprout_generated_utterance":
      return (
        <>
          <p>
            Generated by Sprout · Delivery not established · {event.state}: {event.text}
          </p>
          <p>
            Provider/media: {event.startMs}–{event.endMs} ms · Observed: {event.firstObservedAtMs}–
            {event.lastObservedAtMs} ms
          </p>
        </>
      );
    case "microphone_speech_started":
      return <p>Microphone speech started · observed by app (approximate VAD)</p>;
    case "microphone_speech_stopped":
      return (
        <p>
          Microphone speech stopped · observed by app · Quiet: {event.quietMs} ms · Estimated acoustic end:{" "}
          {event.estimatedAcousticEndAtMs} ms
        </p>
      );
    case "playback_gate_changed":
      return (
        <p>
          Sprout playback {event.state} · {event.reason} · Permission does not establish utterance delivery
        </p>
      );
    case "answer_evaluation_requested":
      return (
        <p>
          Answer evaluation requested · Scene {event.sceneIndex} · {event.correlationKey} · {event.turnSignal} · Turn
          end to request: {event.turnEndToRequestMs} ms
        </p>
      );
    case "answer_evaluation_resolved":
      return (
        <p>
          Answer evaluation resolved · {event.correlationKey} · {event.status} · Latency: {event.latencyMs} ms ·
          Decision: {event.decision} · {event.reason ?? event.model}{" "}
          {event.probability === undefined ? "" : `Control probability: ${event.probability}`}
        </p>
      );
    case "scene_advance_committed":
      return (
        <p>
          Scene advance committed · {event.fromScene} → {event.toScene} · {event.correlationKey}
        </p>
      );
    case "evaluation_control":
      return (
        <p>
          Evaluation control · {event.action} · {event.correlationKey ?? "unassociated"}
          {event.sceneIndex === undefined ? "" : ` · scene ${event.sceneIndex}`}
          {event.transcriptRevision === undefined ? "" : ` · revision ${event.transcriptRevision}`}
          {event.answerVersion ? ` · answer ${event.answerVersion}` : ""}
          {event.sourceId === undefined ? "" : ` · source ${event.sourceId}`}
          {event.delegationId ? ` · delegation ${event.delegationId}` : ""}
          {event.offsetMs === undefined ? "" : ` · provider offset ${event.offsetMs} ms`}
          {event.origin ? ` · origin ${event.origin}` : ""}
          {event.status ? ` · work ${event.status}` : ""}
          {event.result ? ` · result ${event.result}` : ""}
          {event.applicationAction ? ` · action ${event.applicationAction}` : ""}
          {event.displayStatus ? ` · display ${event.displayStatus}` : ""}
          {event.contextEventId ? ` · context ${event.contextEventId}` : ""}
          {event.ackState ? ` · acknowledgment ${event.ackState}` : ""}
          {event.reason ? ` · ${event.reason}` : ""}
        </p>
      );
  }
}

const integrity = {
  pending: [
    "Record still pending",
    "Durable assembly has not finished. Audio attachment or other evidence may still be missing. Refresh to check again.",
  ],
  incomplete: ["Record incomplete", "Some evidence may be missing. Available durable evidence is shown below."],
  complete: [
    "Record complete",
    "Required MVP durable evidence, including full-session audio, was assembled successfully.",
  ],
};

export function SessionRecordView({ record }: { record: InspectableSessionRecord }) {
  const audio = useRef<HTMLAudioElement>(null);
  const [playError, setPlayError] = useState(false);
  function seek(atMs: number) {
    const player = audio.current;
    if (!player || !record.recording) return;
    const offset = recordingOffsetSeconds(atMs, record.recording);
    player.currentTime = Number.isFinite(player.duration) ? Math.min(player.duration, offset) : offset;
    setPlayError(false);
    void player.play().catch(error => {
      // Pausing/seeking again can interrupt a pending play request normally.
      if (error instanceof DOMException && error.name === "AbortError") return;
      setPlayError(true);
    });
  }
  return (
    <>
      {record.state === "ended" && (
        <ParentReviewPanel
          key={record.id}
          sessionId={record.id}
          seek={seek}
          hasRecording={Boolean(record.recording)}
          canRetry={record.recordStatus !== "pending" && Boolean(record.recording)}
        />
      )}
      <p role="status">{integrity[record.recordStatus][0]}</p>
      {record.recordStatus !== "complete" && <p>{integrity[record.recordStatus][1]}</p>}
      <details className="recording-review">
        <summary>Check the recording</summary>
        <details className="developer-inspection">
          <summary>Developer inspection</summary>
          <p>Session: {record.id}</p>
          <p>
            Lifecycle: {record.state} · Ending reason: {record.endingReason ?? "Unavailable"}
          </p>
          <p>{integrity[record.recordStatus][1]}</p>
          <p>Created: {new Date(record.createdAt).toISOString()}</p>
          <p>Started: {record.startedAt === undefined ? "Unavailable" : new Date(record.startedAt).toISOString()}</p>
          <p>Ended: {record.endedAt === undefined ? "Unavailable" : new Date(record.endedAt).toISOString()}</p>
          {record.retryOf && <p>Retry of {record.retryOf}</p>}
        </details>
        {record.recording ? (
          <>
            <p>
              Full-session audio available · {record.recording.mimeType} · {record.recording.durationMs} ms
            </p>
            <audio ref={audio} controls src={record.recording.url} aria-label="Full-session recording" />
            <p>Evidence times start at session.started = 0 ms. Playback positions are approximate.</p>
            {playError && <p role="alert">Playback could not start. Use the audio player to try again.</p>}
          </>
        ) : (
          <p>Full-session audio unavailable.</p>
        )}
        <h3>Recorded speech, scenes and help</h3>
        <p>
          Generated text describes provider output; full recording retains the captured audio. Analysis events are not
          learner evidence.
        </p>
        {!record.events.length && <p>No durable evidence events recorded.</p>}
        <ol>
          {[...record.events]
            .sort((a, b) => a.atMs - b.atMs || a.order - b.order)
            .map(event => (
              <li key={event.eventKey}>
                <p>
                  Event {event.order} · {event.atMs} ms from session.started
                </p>
                {event.evidence && (
                  <>
                    <p>Learner-experience evidence</p>
                    <EvidenceDetail evidence={event.evidence} />
                  </>
                )}
                {event.timeline && (
                  <>
                    <details>
                      <summary>Conversation analysis</summary>
                      <TimelineDetail event={event.timeline} />
                    </details>
                  </>
                )}
                {record.recording && (
                  <button className="download-button" onClick={() => seek(event.atMs)}>
                    Play from here
                  </button>
                )}
              </li>
            ))}
        </ol>
      </details>
    </>
  );
}

export function SessionInspector({
  sessionRef,
  reader,
  onRetry,
}: {
  sessionRef?: DurableSessionRef;
  reader: SessionRecordReader;
  onRetry: (ref: DurableSessionRef) => void;
}) {
  const [record, setRecord] = useState<InspectableSessionRecord | null>(null);
  const [loading, setLoading] = useState(Boolean(sessionRef));
  const [error, setError] = useState(false);
  const [revision, setRevision] = useState(0);
  useEffect(() => {
    if (!sessionRef) return;
    let cancelled = false;
    reader
      .getRecord(sessionRef)
      .then(value => {
        if (!cancelled) {
          setRecord(value);
          setLoading(false);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setError(true);
          setLoading(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, [sessionRef, reader, revision]);
  return (
    <section className="diagnostics" aria-label="Durable session record">
      <h2>Daily check-in</h2>
      {loading && <p role="status">Loading durable session record…</p>}
      {!sessionRef || (!loading && !record) ? (
        <p>
          Durable session record unavailable{error ? ": fetching failed" : ""}. Local prototype diagnostics may still be
          available.
        </p>
      ) : null}
      {error && record && <p role="alert">Refresh failed. Showing the previously fetched record.</p>}
      {record && <SessionRecordView record={record} />}
      {sessionRef && (
        <button
          className="download-button"
          disabled={loading}
          onClick={() => {
            setLoading(true);
            setError(false);
            setRevision(value => value + 1);
          }}
        >
          Refresh record
        </button>
      )}
      {record?.state === "ended" && (
        <button className="download-button" onClick={() => onRetry(record.id)}>
          Retry this lesson
        </button>
      )}
    </section>
  );
}
