import type { TimelineEvent } from "../lib/session-recorder";

export function TimelineDetail({ event }: { event: TimelineEvent }) {
  switch (event.type) {
    case "sprout_generated_utterance":
      return (
        <>
          <p>
            Generated by Sprout · Delivery not established · {event.state}: {event.text}
          </p>
          <p>
            Provider/media: {event.startMs}–{event.endMs} ms · Observed: {event.firstObservedAtMs}–
            {event.lastObservedAtMs} ms
          </p>
        </>
      );
    case "microphone_speech_started":
      return <p>Microphone speech started · observed by app (approximate VAD)</p>;
    case "microphone_speech_stopped":
      return (
        <p>
          Microphone speech stopped · observed by app · Quiet: {event.quietMs} ms · Estimated acoustic end:{" "}
          {event.estimatedAcousticEndAtMs} ms
        </p>
      );
    case "playback_gate_changed":
      return (
        <p>
          Sprout playback {event.state} · {event.reason} · Permission does not establish utterance delivery
        </p>
      );
  }
}
