import type { TimelineEvent } from "../lib/session-recorder";

export function TimelineDetail({ event }: { event: TimelineEvent }) {
  switch (event.type) {
    case "local_playback":
      return (
        <p>
          Local finite speech · {event.role} · {event.state}: {event.text} · {event.display.sceneId} ·{" "}
          {event.identity.playbackAttemptId} · {event.reason ?? ""} ·{" "}
          {event.state === "completed"
            ? "Browser output fence passed; hearing unverified"
            : "Whole instruction delivery not established"}
        </p>
      );
    case "choreography_phase":
      return (
        <p>
          Application choreography · {event.phase} · {event.display.sceneId} · Question: {event.questionStatus} ·{" "}
          {event.reason ?? ""}
        </p>
      );
    case "sprout_generated_utterance":
      return (
        <>
          <p>
            Generated by Sprout · Delivery not established · {event.state}: {event.text}
          </p>
          <p>
            Provider/media: {event.startMs}–{event.endMs} ms · Observed: {event.firstObservedAtMs}–
            {event.lastObservedAtMs} ms
          </p>
        </>
      );
    case "help_delivery_candidate":
      return (
        <p>
          Generated {event.kind === "instructional_help" ? "instructional help" : "neutral clarification"} · Delivery{" "}
          {event.delivery} · Transcript {event.transcriptState} · Source {event.sourceId ?? "unknown"} · Display{" "}
          {event.displayStatus}
          {event.display ? ` (${event.display.sceneId}, shown at ${event.display.displayedAtMs} ms)` : " (unknown)"} ·
          Provider transcript time {event.startMs}–{event.endMs} ms is not a recording seek point: {event.text}
        </p>
      );
    case "microphone_speech_started":
      return <p>Microphone speech started · observed by app (approximate VAD)</p>;
    case "microphone_speech_stopped":
      return (
        <p>
          Microphone speech stopped · observed by app · Quiet: {event.quietMs} ms · Estimated acoustic end:{" "}
          {event.estimatedAcousticEndAtMs} ms
        </p>
      );
    case "playback_gate_changed":
      return (
        <p>
          Sprout playback {event.state} · {event.reason} · Permission does not establish utterance delivery
        </p>
      );
    case "answer_evaluation_requested":
      return (
        <p>
          Answer evaluation requested · Scene {event.sceneIndex} · {event.correlationKey} · {event.turnSignal} · Turn
          end to request: {event.turnEndToRequestMs} ms
        </p>
      );
    case "answer_evaluation_resolved":
      return (
        <p>
          Answer evaluation resolved · {event.correlationKey} · {event.status} · Latency: {event.latencyMs} ms ·
          Decision: {event.decision} · {event.reason ?? event.model}{" "}
          {event.probability === undefined ? "" : `Control probability: ${event.probability}`}
        </p>
      );
    case "scene_advance_committed":
      return (
        <p>
          Scene advance committed · {event.fromScene} → {event.toScene} · {event.correlationKey}
        </p>
      );
    case "evaluation_control":
      return (
        <p>
          Evaluation control · {event.action} · {event.correlationKey ?? "unassociated"}
          {event.sceneIndex === undefined ? "" : ` · scene ${event.sceneIndex}`}
          {event.transcriptRevision === undefined ? "" : ` · revision ${event.transcriptRevision}`}
          {event.answerVersion ? ` · answer ${event.answerVersion}` : ""}
          {event.sourceId === undefined ? "" : ` · source ${event.sourceId}`}
          {event.delegationId ? ` · delegation ${event.delegationId}` : ""}
          {event.offsetMs === undefined ? "" : ` · provider offset ${event.offsetMs} ms`}
          {event.origin ? ` · origin ${event.origin}` : ""}
          {event.status ? ` · work ${event.status}` : ""}
          {event.result ? ` · result ${event.result}` : ""}
          {event.applicationAction ? ` · action ${event.applicationAction}` : ""}
          {event.displayStatus ? ` · display ${event.displayStatus}` : ""}
          {event.contextEventId ? ` · context ${event.contextEventId}` : ""}
          {event.ackState ? ` · acknowledgment ${event.ackState}` : ""}
          {event.reason ? ` · ${event.reason}` : ""}
        </p>
      );
  }
}
